<a href="https://colab.research.google.com/github/MaryGakpan/Tuesday/blob/main/Assign1_000518596.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a.	Generate a two-dimensional integer array with the shape of (20,5) and name it “data”. Fill “data” with random integers from -100 to 100. Display “data” at the end.

In [ ]:
import numpy as np
data = np.random.randint(-100, 101, size=(20, 5)) #Generating the 20x5 array with random integers from -100 to 100
print("The generated 20 by 5 integer array 'data' is:")

print(data)

The generated 20 by 5 integer array 'data' is:
[[ -36    4   82   82  -46]
 [ -68  -62  -88   95   19]
 [ -42  -90  -28  -43   17]
 [ -18  -32   50   91    2]
 [  74  -16   98   27   91]
 [ -62   90  -59   54  -15]
 [ -54   58  -85   72  -82]
 [ -39  -40  -12   38   44]
 [ -77  -46   90  -32   10]
 [  -6   82   81    0  -58]
 [  81    3   14    3  -64]
 [  39   60  -10 -100  -57]
 [  83   28   89  -89   -1]
 [ -73  -16  -76   37   46]
 [ -61  -57   88  -24   15]
 [ -28  -34   -2   20  -72]
 [  41  -20  -40  -40  -69]
 [  15   60  -17   30   80]
 [ -16   49   14  -12  -14]
 [ -53  -97    1  -59   80]]


b.	Display the average value of the third column in “data”

In [ ]:
import numpy as np
average_third_column = np.mean(data[:, 2]) # 'data' is a NumPy array and the third column is index 2


print(f"The average value of the third column is: {average_third_column:.2f}")

The average value of the third column is: 9.50


c.	Display the average value of the first 5 rows in “data”

In [ ]:
import numpy as np
average_first_five_rows = np.mean(data[:5]) #finding average for first five rows

print(f"The average value of the first 5 rows in 'data' is: {average_first_five_rows:.2f}") #displaying my answer in two decimal places

The average value of the first 5 rows in 'data' is: 6.52


d.	Display the average value of the first 3 rows and the 4th column in “data”.

In [ ]:
import numpy as np
first_three_rows = data[:3]  #average of the first three rows
fourth_column = data[:, 3]   #average of the fourth column
average_first_three_rows_4th_column = np.mean(first_three_rows[:, 3]) #Calculate and display the average value of the first 3 rows and the 4th column

print(f"The average value of the first 3 rows and the 4th column is: {average_first_three_rows_4th_column:.2f}") #displaying my answer in two decimal places

The average value of the first 3 rows and the 4th column is: 44.67


e.	Create a new NumPy array which contains the last 4 elements of the second row of “data”.  Display the new array at the end.

In [ ]:
import numpy as np
second_row = data[1, -4:]  #Creating a new numpy array containing the last four elements of the 2nd row
print("My new NumPy array with the last 4 elements of the second row:")

print(second_row)

My new NumPy array with the last 4 elements of the second row:
[-62 -88  95  19]


f.	Reshape “data” int to 10 x 10 matrix.  Display the matrix at the end.

In [ ]:
import numpy as np
reshaped_data = data.reshape(10, 10)  #Reshaping 'data' to a 10 x 10 matrix
print("Reshaped 10 by 10 matrix is:")

print(reshaped_data)

Reshaped 10 by 10 matrix is:
[[ -36    4   82   82  -46  -68  -62  -88   95   19]
 [ -42  -90  -28  -43   17  -18  -32   50   91    2]
 [  74  -16   98   27   91  -62   90  -59   54  -15]
 [ -54   58  -85   72  -82  -39  -40  -12   38   44]
 [ -77  -46   90  -32   10   -6   82   81    0  -58]
 [  81    3   14    3  -64   39   60  -10 -100  -57]
 [  83   28   89  -89   -1  -73  -16  -76   37   46]
 [ -61  -57   88  -24   15  -28  -34   -2   20  -72]
 [  41  -20  -40  -40  -69   15   60  -17   30   80]
 [ -16   49   14  -12  -14  -53  -97    1  -59   80]]


g.	Calculate the std deviation of “data”

In [ ]:
import numpy as np
std_dev = np.std(data) #calculating standard deviation

print(f"The standard deviation of 'data' is:{std_dev:.2f} ") #displaying my answer in two decimal places

The standard deviation of 'data' is:56.01 


h.	Replace the most largest number of each row in “data” with the average of the corresponding row.  Display “data” at the end.

In [ ]:
import numpy as np
row_averages = np.mean(data, axis=1, keepdims=True) #Calculating the average of each row
max_num = data == np.max(data, axis=1, keepdims=True) #Creating a boolean mask to identify the positions of the maximum values in each row
data = np.where(max_num, row_averages, data) #Replacing the maximum value with the corresponding row average

data

array([[ -36. ,    4. ,   17.2,   17.2,  -46. ],
       [ -68. ,  -62. ,  -88. ,  -20.8,   19. ],
       [ -42. ,  -90. ,  -28. ,  -43. ,  -37.2],
       [ -18. ,  -32. ,   50. ,   18.6,    2. ],
       [  74. ,  -16. ,   54.8,   27. ,   91. ],
       [ -62. ,    1.6,  -59. ,   54. ,  -15. ],
       [ -54. ,   58. ,  -85. ,  -18.2,  -82. ],
       [ -39. ,  -40. ,  -12. ,   38. ,   -1.8],
       [ -77. ,  -46. ,  -11. ,  -32. ,   10. ],
       [  -6. ,   19.8,   81. ,    0. ,  -58. ],
       [   7.4,    3. ,   14. ,    3. ,  -64. ],
       [  39. ,  -13.6,  -10. , -100. ,  -57. ],
       [  83. ,   28. ,   22. ,  -89. ,   -1. ],
       [ -73. ,  -16. ,  -76. ,   37. ,  -16.4],
       [ -61. ,  -57. ,   -7.8,  -24. ,   15. ],
       [ -28. ,  -34. ,   -2. ,  -23.2,  -72. ],
       [ -25.6,  -20. ,  -40. ,  -40. ,  -69. ],
       [  15. ,   60. ,  -17. ,   30. ,   33.6],
       [ -16. ,    4.2,   14. ,  -12. ,  -14. ],
       [ -53. ,  -97. ,    1. ,  -59. ,  -25.6]])

i.	Create a new NumPy array which contains random 2 rows in “data”.  Display the new array at the end.

In [ ]:
import numpy as np
random_rows_indices = np.random.choice(data.shape[0], size=2, replace=False) #Generating random row indices for the new array
random_rows = data[random_rows_indices]  #Creating a new NumPy array with the selected rows
print("My new NumPy array with 2 random rows is:")

print(random_rows)

My new NumPy array with 2 random rows is:
[[-36.    4.   17.2  17.2 -46. ]
 [ -6.   19.8  81.    0.  -58. ]]


j.	Create a new NumPy array which contains random 3 columns in “data” .  Display the new array at the end.

In [ ]:
import numpy as np
num_columns = data.shape[1]
random_column_indices = np.random.choice(num_columns, size=3, replace=False) #Generating random column indices for the new array
random_columns = data[:, random_column_indices]  #Creating a new NumPy array with the selected columns
print("My new NumPy array with 3 random columns is:")

print(random_columns)

My new NumPy array with 3 random columns is:
[[  4.   17.2 -46. ]
 [-62.  -88.   19. ]
 [-90.  -28.  -37.2]
 [-32.   50.    2. ]
 [-16.   54.8  91. ]
 [  1.6 -59.  -15. ]
 [ 58.  -85.  -82. ]
 [-40.  -12.   -1.8]
 [-46.  -11.   10. ]
 [ 19.8  81.  -58. ]
 [  3.   14.  -64. ]
 [-13.6 -10.  -57. ]
 [ 28.   22.   -1. ]
 [-16.  -76.  -16.4]
 [-57.   -7.8  15. ]
 [-34.   -2.  -72. ]
 [-20.  -40.  -69. ]
 [ 60.  -17.   33.6]
 [  4.2  14.  -14. ]
 [-97.    1.  -25.6]]


k.	Create a new NumPy array which contains 100 random doubles drawn from a normal (Gaussian) distribution.  Display the new array at the end.

In [ ]:
import numpy as np
data1 = np.random.normal(size=100) #Generating an array named 'data1' with 100 random doubles from a normal (Gaussian) distribution
print("My new NumPy array with 100 random doubles from a normal (Gaussian) distribution is:")

print(data1)

My new NumPy array with 100 random doubles from a normal (Gaussian) distribution is:
[-0.83506122 -1.58570622 -0.63170502 -1.38050246  0.51616632  0.52082697
 -0.98363164 -0.76564879 -2.54238069  0.35112006 -1.75717557  0.31514584
 -0.56979921  0.01318707 -0.01201736  0.13476326  0.31559768  0.56428058
 -0.74738313 -1.09505146  0.19650476  0.26848467 -0.18192795  0.6660533
 -0.9043068  -0.3579822   0.92591342  0.7905241   3.231388    0.57805849
  0.86228167  0.72636996  0.61314364 -0.02597467  1.33289616 -1.29660888
 -0.48162778 -1.22030814  0.34853877 -0.28691202 -0.419332   -0.98995775
  0.56837675  0.32011046  0.30795294 -0.24410835 -0.94662757  1.19628268
  0.53079632 -0.23622863 -0.43023197 -0.08098202 -1.15346619  0.9649409
  0.83349757  1.14988301  0.21992606  0.24991934  1.541777   -0.90286575
 -0.83219811  1.63067042  0.35315405 -1.27147283 -1.37103724  0.4328292
 -0.22695202  0.93313026  0.99859559 -0.17815772 -2.16040177 -0.96811774
 -0.69120811  1.56844362 -1.39300827  0.26

l.	Convert the data to a Panda Data Frame with the header “a” – “e” and name it “dataframe”. Describe the “dataframe” at the end.  

In [ ]:
import pandas as pd
import numpy as np
dataframe = pd.DataFrame(data, columns=['a', 'b', 'c', 'd', 'e'])  #Creating a Pandas DataFrame with the specified column headers
description = dataframe.describe() #Describing the DataFrame

dataframe, description

(       a     b     c      d     e
 0  -36.0   4.0  17.2   17.2 -46.0
 1  -68.0 -62.0 -88.0  -20.8  19.0
 2  -42.0 -90.0 -28.0  -43.0 -37.2
 3  -18.0 -32.0  50.0   18.6   2.0
 4   74.0 -16.0  54.8   27.0  91.0
 5  -62.0   1.6 -59.0   54.0 -15.0
 6  -54.0  58.0 -85.0  -18.2 -82.0
 7  -39.0 -40.0 -12.0   38.0  -1.8
 8  -77.0 -46.0 -11.0  -32.0  10.0
 9   -6.0  19.8  81.0    0.0 -58.0
 10   7.4   3.0  14.0    3.0 -64.0
 11  39.0 -13.6 -10.0 -100.0 -57.0
 12  83.0  28.0  22.0  -89.0  -1.0
 13 -73.0 -16.0 -76.0   37.0 -16.4
 14 -61.0 -57.0  -7.8  -24.0  15.0
 15 -28.0 -34.0  -2.0  -23.2 -72.0
 16 -25.6 -20.0 -40.0  -40.0 -69.0
 17  15.0  60.0 -17.0   30.0  33.6
 18 -16.0   4.2  14.0  -12.0 -14.0
 19 -53.0 -97.0   1.0  -59.0 -25.6,
                a          b          c           d          e
 count  20.000000  20.000000  20.000000   20.000000  20.000000
 mean  -22.010000 -17.250000  -9.090000  -11.820000 -19.420000
 std    46.046497  42.195628  45.255507   41.745893  42.787499
 min   -77.0

m.	Save the “dataframe” into assign1.xlsx.

In [ ]:
dataframe.to_excel("assign1.xlsx", index=False)

n.	Save the “dataframe” into assign1.csv.

In [ ]:
dataframe.to_csv("assign1.csv", index=False)

o.	Replace all the negative numbers in “dataframe” to 0. Describe the “dataframe” at the end.  

In [ ]:
dataframe[dataframe < 0] = 0 #Replacing all negative numbers with 0 in the 'dataframe
description = dataframe.describe()

dataframe, description

(       a     b     c     d     e
 0    0.0   4.0  17.2  17.2   0.0
 1    0.0   0.0   0.0   0.0  19.0
 2    0.0   0.0   0.0   0.0   0.0
 3    0.0   0.0  50.0  18.6   2.0
 4   74.0   0.0  54.8  27.0  91.0
 5    0.0   1.6   0.0  54.0   0.0
 6    0.0  58.0   0.0   0.0   0.0
 7    0.0   0.0   0.0  38.0   0.0
 8    0.0   0.0   0.0   0.0  10.0
 9    0.0  19.8  81.0   0.0   0.0
 10   7.4   3.0  14.0   3.0   0.0
 11  39.0   0.0   0.0   0.0   0.0
 12  83.0  28.0  22.0   0.0   0.0
 13   0.0   0.0   0.0  37.0   0.0
 14   0.0   0.0   0.0   0.0  15.0
 15   0.0   0.0   0.0   0.0   0.0
 16   0.0   0.0   0.0   0.0   0.0
 17  15.0  60.0   0.0  30.0  33.6
 18   0.0   4.2  14.0   0.0   0.0
 19   0.0   0.0   1.0   0.0   0.0,
                a          b         c          d          e
 count  20.000000  20.000000  20.00000  20.000000  20.000000
 mean   10.920000   8.930000  12.70000  11.240000   8.530000
 std    24.900678  18.624181  22.95428  16.986137  21.330411
 min     0.000000   0.000000   0.00000   

p.	Replace all the zeros in the “dataframe” to 1. Describe the “dataframe” at the end.  

In [ ]:
dataframe[dataframe == 0] = 1 #Replacing all zeros with 1 in the 'dataframe'
description = dataframe.describe()

dataframe, description

(       a     b     c     d     e
 0    1.0   4.0  17.2  17.2   1.0
 1    1.0   1.0   1.0   1.0  19.0
 2    1.0   1.0   1.0   1.0   1.0
 3    1.0   1.0  50.0  18.6   2.0
 4   74.0   1.0  54.8  27.0  91.0
 5    1.0   1.6   1.0  54.0   1.0
 6    1.0  58.0   1.0   1.0   1.0
 7    1.0   1.0   1.0  38.0   1.0
 8    1.0   1.0   1.0   1.0  10.0
 9    1.0  19.8  81.0   1.0   1.0
 10   7.4   3.0  14.0   3.0   1.0
 11  39.0   1.0   1.0   1.0   1.0
 12  83.0  28.0  22.0   1.0   1.0
 13   1.0   1.0   1.0  37.0   1.0
 14   1.0   1.0   1.0   1.0  15.0
 15   1.0   1.0   1.0   1.0   1.0
 16   1.0   1.0   1.0   1.0   1.0
 17  15.0  60.0   1.0  30.0  33.6
 18   1.0   4.2  14.0   1.0   1.0
 19   1.0   1.0   1.0   1.0   1.0,
                a         b         c          d          e
 count  20.000000  20.00000  20.00000  20.000000  20.000000
 mean   11.670000   9.53000  13.30000  11.840000   9.230000
 std    24.556039  18.32574  22.60773  16.570564  21.038939
 min     1.000000   1.00000   1.00000   1.000